# ==========================================
# APPLICATION CONFIG
# ==========================================
spring.application.name=lost-and-found-service
server.port=${SERVER_PORT:8083}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ==========================================
# MONGODB
# ==========================================
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ReunionSphere_LostAndFoundService}
spring.mongodb.database=${MONGODB_DATABASE:Report_Db}

# ==========================================
# CLOUDINARY
# ==========================================
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ==========================================
# REDIS CACHE
# ==========================================
spring.cache.type=${CACHE_TYPE:redis}
spring.data.redis.host= ${CACHE_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# ==========================================
# MULTIPART FILE CONFIG
# ==========================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# ==========================================
# KAFKA
# ==========================================
# spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# spring.kafka.consumer.group-id=lost-found-group
# spring.kafka.consumer.auto-offset-reset=earliest
# spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
# spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# spring.kafka.consumer.properties.spring.json.trusted.packages=*


# ==========================================
# FEIGN CLIENTS
# ==========================================
services.user-service.url=${USER_SERVICE_URL}
services.notification-service.url=${NOTIFICATION_SERVICE_URL}
services.subscription-service.url=${SUBSCRIPTION_SERVICE_URL}

# ==========================================
# SWAGGER
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================================
# ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=health,info,metrics

# ==========================================
# LOGGING
# ==========================================
logging.level.com.reunionsphere.lostfound=DEBUG
logging.level.org.springframework.data.mongodb=INFO

# TimeZone
spring.jackson.time-zone=Asia/Kolkata

# JWT Config
jwt.secret=${JWT_SECRET:8mB8Y4M5rL8mN2vA7sK4hQ6dF1gJ9xT3uC5eW7rP2zY6nL0kB1}
